# Generated by Django 2.0 on 2021-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('contect', models.BigIntegerField(default=123456789)),
                ('email', models.EmailField(default='email@gmail.com', max_length=254, unique=True)),
                ('Hobby', models.CharField(default='hobby', max_length=255)),
            ],
        ),
    ]
