# Generated by Django 2.0 on 2021-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_us_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='us_file',
            name='o_file',
            field=models.FileField(default='.xls', upload_to='file/'),
        ),
    ]
